databases:
  - name: Budget-Tracker
    databaseName: budget_tracker_syej
    user: budget_tracker_syej_user

services:
  - type: web
    name: Makena
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Budget-Tracker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false